# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: ["--py312-plus"]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
    -   id: pretty-format-yaml
        args:
        -   --autofix
        -   --preserve-quotes
        -   --indent=4
    -   id: pretty-format-toml
        args:
        -   --autofix
        -   --indent=4

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: mypy
        name: Validate types with MyPy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
        args:
        -   "src"
