name: 🦺 Type checking

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]
    release:
        types: [released]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:

    tests:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.12"]

        steps:

        -   name: Checkout
            uses: actions/checkout@v4
        -   name: Install uv
            uses: astral-sh/setup-uv@v2
        -   name: Install deps
            run: uv sync --frozen

        -   name: Run type checker apiserver
            run: uv run pyright ./src/**
